In [18]:
import pandas as pd

In [19]:
regionData = pd.read_csv("../dataset/analysis_list/region_code.csv")
loadShopData = pd.read_csv("../dataset/analysis_list/seoul_load_shop_list.csv")
peopleData = pd.read_csv("../dataset/analysis_list/seoul_move_people_list.csv")
restaurantData = pd.read_csv("../dataset/analysis_list/sinsa_restaurant_list.csv")

In [20]:
loadShopData

,STDR_YM_CD,TRDAR_SE_CD,TRDAR_SE_CD_NM,TRDAR_CD,TRDAR_CD_NM,SIGNGU_CD,ADSTRD_CD
0,202112,A,골목상권,2110753,시흥동 은행나무사거리,11545,1154571000
1,202112,A,골목상권,2110427,노원 을지대학교병원,11350,1135061100
2,202112,A,골목상권,2110755,동일여자고등학교,11545,1154568000
3,202112,A,골목상권,2110739,시흥3동 우편취급국,11545,1154569000
4,202112,A,골목상권,2111017,송파나루역 3번,11710,1171056200
...,...,...,...,...,...,...,...
1666,202112,U,관광특구,1001493,동대문패션타운 관광특구,11140,1114059000
1667,202112,U,관광특구,1001494,종로?청계 관광특구,11110,1111061500
1668,202112,U,관광특구,1001495,잠실 관광특구,11710,1171056600
1669,202112,U,관광특구,1001496,강남 마이스 관광특구,11680,1168058000
1670,202112,U,관광특구,1001491,이태원 관광특구,11170,1117065000

In [21]:
regionData

       ADSTRD_CD         REGION_ID REGION_SI REGION_GU REGION_DONG
0     1100000000           서울특별시       서울특별시       NaN         NaN
1     1111000000        서울특별시 종로구      서울특별시       종로구         NaN
2     1111051500   서울특별시 종로구 청운효자동     서울특별시       종로구       청운효자동
3     1111053000     서울특별시 종로구 사직동     서울특별시       종로구         사직동
4     1111054000     서울특별시 종로구 삼청동     서울특별시       종로구         삼청동
...          ...               ...       ...       ...         ...
3783  5013060000  제주특별자치도 서귀포시 대천동   제주특별자치도      서귀포시         대천동
3784  5013061000  제주특별자치도 서귀포시 중문동   제주특별자치도      서귀포시         중문동
3785  5013062000  제주특별자치도 서귀포시 예래동   제주특별자치도      서귀포시         예래동
3786  5019000000             이어도         이어도       NaN         NaN
3787  5019099000             이어도         이어도       NaN         NaN

[3788 rows x 5 columns]

In [30]:
### 상권지역 상세 법정동 조인
detailLoadData = pd.merge(left=loadShopData,
                          right=regionData,
                          left_on=["ADSTRD_CD"],
                          right_on=["ADSTRD_CD"], how="left")

In [31]:
detailLoadData

,STDR_YM_CD,TRDAR_SE_CD,TRDAR_SE_CD_NM,TRDAR_CD,TRDAR_CD_NM,SIGNGU_CD,ADSTRD_CD,REGION_ID,REGION_SI,REGION_GU,REGION_DONG
0,202112,A,골목상권,2110753,시흥동 은행나무사거리,11545,1154571000,서울특별시 금천구 시흥제5동,서울특별시,금천구,시흥제5동
1,202112,A,골목상권,2110427,노원 을지대학교병원,11350,1135061100,서울특별시 노원구 하계1동,서울특별시,노원구,하계1동
2,202112,A,골목상권,2110755,동일여자고등학교,11545,1154568000,서울특별시 금천구 시흥제2동,서울특별시,금천구,시흥제2동
3,202112,A,골목상권,2110739,시흥3동 우편취급국,11545,1154569000,서울특별시 금천구 시흥제3동,서울특별시,금천구,시흥제3동
4,202112,A,골목상권,2111017,송파나루역 3번,11710,1171056200,서울특별시 송파구 방이2동,서울특별시,송파구,방이2동
...,...,...,...,...,...,...,...,...,...,...,...
1666,202112,U,관광특구,1001493,동대문패션타운 관광특구,11140,1114059000,서울특별시 중구 광희동,서울특별시,중구,광희동
1667,202112,U,관광특구,1001494,종로?청계 관광특구,11110,1111061500,서울특별시 종로구 종로1.2.3.4가동,서울특별시,종로구,종로1.2.3.4가동
1668,202112,U,관광특구,1001495,잠실 관광특구,11710,1171056600,서울특별시 송파구 오륜동,서울특별시,송파구,오륜동
1669,202112,U,관광특구,1001496,강남 마이스 관광특구,11680,1168058000,서울특별시 강남구 삼성1동,서울특별시,강남구,삼성1동
1670,202112,U,관광특구,1001491,이태원 관광특구,11170,1117065000,서울특별시 용산구 이태원제1동,서울특별시,용산구,이태원제1동

In [38]:
### 서울 강남구 신사동 내 상권 정보 추출
sinsaLoadData = detailLoadData.loc[(detailLoadData["REGION_SI"] == "서울특별시") & (detailLoadData["REGION_GU"] == "강남구") & (detailLoadData["REGION_DONG"] == "신사동")]

In [39]:
sinsaLoadData

,STDR_YM_CD,TRDAR_SE_CD,TRDAR_SE_CD_NM,TRDAR_CD,TRDAR_CD_NM,SIGNGU_CD,ADSTRD_CD,REGION_ID,REGION_SI,REGION_GU,REGION_DONG
82,202112,A,골목상권,2110949,한남IC,11680,1168051000,서울특별시 강남구 신사동,서울특별시,강남구,신사동
509,202112,A,골목상권,2110951,신사은행나무공원,11680,1168051000,서울특별시 강남구 신사동,서울특별시,강남구,신사동
1231,202112,D,발달상권,2120186,가로수길,11680,1168051000,서울특별시 강남구 신사동,서울특별시,강남구,신사동
1287,202112,D,발달상권,2120188,압구정역,11680,1168051000,서울특별시 강남구 신사동,서울특별시,강남구,신사동
1492,202112,R,전통시장,2130302,강남시장(강남구 강남시장),11680,1168051000,서울특별시 강남구 신사동,서울특별시,강남구,신사동

In [69]:
loadRestauranData = pd.merge(left=restaurantData,
                            right=sinsaLoadData,
                            left_on=["ADSTRD_CD"],
                            right_on=["ADSTRD_CD"], how="right")

In [74]:
### 상권 구역별 음식점 리스트 조인
### 나중에 여러분들이 수집한 음식점 리스트 주소를 여기에 조인
hanNamIc = loadRestauranData.loc[(loadRestauranData["TRDAR_CD_NM"] == "한남IC")]

sinsaPark = loadRestauranData.loc[(loadRestauranData["TRDAR_CD_NM"] == "신사은행나무공원")]

garosugill = loadRestauranData.loc[(loadRestauranData["TRDAR_CD_NM"] == "가로수길")]

apgujungSt = loadRestauranData.loc[(loadRestauranData["TRDAR_CD_NM"] == "압구정역")]

gangnamMk = loadRestauranData.loc[(loadRestauranData["TRDAR_CD_NM"] == "강남시장(강남구 강남시장)")]

In [96]:
peopleLoadData = pd.merge(left=sinsaLoadData,
                            right=peopleData,
                            left_on=["TRDAR_CD"],
                            right_on=["TRDAR_CD"], how="left").drop_duplicates(["TRDAR_CD"])

In [98]:
### 상권 구역별 연령, 성별 유동인구표
### 머신러닝때 사용자가 연령대를 입력하면 5개 지역 중 연령대에 맞게 상권 구역과 음식점 추천 로직으로 만들면 좋을듯... 할 수 있다면...

hanNamPeople = peopleLoadData.loc[(peopleLoadData["TRDAR_CD"] == 2110949)]

sinsaParkPeople = peopleLoadData.loc[(peopleLoadData["TRDAR_CD"] == 2110951)]

garosugillPeople = peopleLoadData.loc[(peopleLoadData["TRDAR_CD"] == 2120186)]

apgujungStPeople = peopleLoadData.loc[(peopleLoadData["TRDAR_CD"] == 2120188)]

gangnamMkPeople = peopleLoadData.loc[(peopleLoadData["TRDAR_CD"] == 2130302)]

In [99]:
hanNamPeople

,STDR_YM_CD,TRDAR_SE_CD_x,TRDAR_SE_CD_NM_x,TRDAR_CD,TRDAR_CD_NM_x,SIGNGU_CD,ADSTRD_CD,REGION_ID,REGION_SI,REGION_GU,...,TMZON_4_FLPOP_CO,TMZON_5_FLPOP_CO,TMZON_6_FLPOP_CO,MON_FLPOP_CO,TUES_FLPOP_CO,WED_FLPOP_CO,THUR_FLPOP_CO,FRI_FLPOP_CO,SAT_FLPOP_CO,SUN_FLPOP_CO
0,202112,A,골목상권,2110949,한남IC,11680,1168051000,서울특별시 강남구 신사동,서울특별시,강남구,...,59838,69269,35408,50066,52565,52565,53414,53798,48440,42143

In [103]:
### 서울 강남구 신사동 내 상권 정보
sinsaLoadData.to_csv('../dataset/analysis_list/sinsa_load_shop_list.csv', index=False, encoding="utf-8-sig")

### 상권 구역별 음식점 리스트 
hanNamIc.to_csv('../dataset/analysis_list/hanNamIc_load_restaurant_list.csv', index=False, encoding="utf-8-sig")
sinsaPark.to_csv('../dataset/analysis_list/sinsaPark_load_restaurant_list.csv', index=False, encoding="utf-8-sig")
garosugill.to_csv('../dataset/analysis_list/garosugill_load_restaurant_list.csv', index=False, encoding="utf-8-sig")
apgujungSt.to_csv('../dataset/analysis_list/apgujungSt_load_restaurant_list.csv', index=False, encoding="utf-8-sig")
gangnamMk.to_csv('../dataset/analysis_list/gangnamMk_load_restaurant_list.csv', index=False, encoding="utf-8-sig")
loadRestauranData.to_csv('../dataset/analysis_list/sinsa_load_restaurant_list.csv', index=False, encoding="utf-8-sig")

### 상권 구역별 연령, 성별 유동인구표 
hanNamPeople.to_csv('../dataset/analysis_list/hanNamIc_people_list.csv', index=False, encoding="utf-8-sig")
sinsaParkPeople.to_csv('../dataset/analysis_list/sinsaPark_people_list.csv', index=False, encoding="utf-8-sig")
garosugillPeople.to_csv('../dataset/analysis_list/garosugill_people_list.csv', index=False, encoding="utf-8-sig")
apgujungStPeople.to_csv('../dataset/analysis_list/apgujungSt_people_list.csv', index=False, encoding="utf-8-sig")
gangnamMkPeople.to_csv('../dataset/analysis_list/gangnamMk_people_list.csv', index=False, encoding="utf-8-sig")
peopleLoadData.to_csv('../dataset/analysis_list/sinsa__people_list.csv', index=False, encoding="utf-8-sig")